name: bridging_labs

environment:
  sdk: ^3.6.0

# For each package provdided here, remember to add
# ```yaml
# environment:
#   sdk: ^3.6.0
# resolution: workspace
# ```
# to the pubspec.yaml file of the package
workspace:
  - packages/lsl_bindings
  - packages/lsl_flutter
  - packages/carp_multicast_lock
  - packages/muse_sdk
  - apps/sensors
  - apps/scripted
  - apps/test_windows
