name: lsl_bindings
description: "A plugin for interacting with the Lab Streeming Layer"
version: 0.0.1
homepage: https://github.com/olafuroskar/Bridging-Labs/tree/main/plugins/lsl_bindings#readme
repository: https://github.com/olafuroskar/Bridging-Labs/tree/main/plugins/lsl_bindings
issue_tracker: https://github.com/olafuroskar/Bridging-Labs/issues

environment:
  sdk: ^3.6.0
  flutter: ">=3.3.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffi: ^2.1.3
  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
