// Mocks generated by Mockito 5.4.5 from annotations
// in lsl_flutter/test/lsl_flutter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ffi' as _i3;

import 'package:lsl_bindings/src/lsl_bindings_generated.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:carp_multicast_lock/carp_multicast_lock.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LslBindings].
///
/// See the documentation for Mockito's code generation for more information.
class MockLslBindings extends _i1.Mock implements _i2.LslBindings {
  @override
  _i3.Pointer<_i2.lsl_outlet_struct_> lsl_create_outlet(
    _i3.Pointer<_i2.lsl_streaminfo_struct_>? info,
    int? chunk_size,
    int? max_buffered,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_create_outlet, [
              info,
              chunk_size,
              max_buffered,
            ]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i2.lsl_outlet_struct_>>(
              this,
              Invocation.method(#lsl_create_outlet, [
                info,
                chunk_size,
                max_buffered,
              ]),
            ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_outlet_struct_>>(
                  this,
                  Invocation.method(#lsl_create_outlet, [
                    info,
                    chunk_size,
                    max_buffered,
                  ]),
                ),
          )
          as _i3.Pointer<_i2.lsl_outlet_struct_>);

  @override
  _i3.Pointer<_i2.lsl_outlet_struct_> lsl_create_outlet_ex(
    _i3.Pointer<_i2.lsl_streaminfo_struct_>? info,
    int? chunk_size,
    int? max_buffered,
    _i2.lsl_transport_options_t? flags,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_create_outlet_ex, [
              info,
              chunk_size,
              max_buffered,
              flags,
            ]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i2.lsl_outlet_struct_>>(
              this,
              Invocation.method(#lsl_create_outlet_ex, [
                info,
                chunk_size,
                max_buffered,
                flags,
              ]),
            ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_outlet_struct_>>(
                  this,
                  Invocation.method(#lsl_create_outlet_ex, [
                    info,
                    chunk_size,
                    max_buffered,
                    flags,
                  ]),
                ),
          )
          as _i3.Pointer<_i2.lsl_outlet_struct_>);

  @override
  void lsl_destroy_outlet(_i3.Pointer<_i2.lsl_outlet_struct_>? out) =>
      super.noSuchMethod(
        Invocation.method(#lsl_destroy_outlet, [out]),
        returnValueForMissingStub: null,
      );

  @override
  int lsl_push_sample_f(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Float>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_f, [out, data]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_d(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Double>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_d, [out, data]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_l(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int64>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_l, [out, data]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_i(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int32>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_i, [out, data]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_s(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int16>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_s, [out, data]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_c(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Char>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_c, [out, data]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_str(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_str, [out, data]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_v(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Void>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_v, [out, data]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_ft(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Float>? data,
    double? timestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_ft, [out, data, timestamp]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_dt(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Double>? data,
    double? timestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_dt, [out, data, timestamp]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_lt(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int64>? data,
    double? timestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_lt, [out, data, timestamp]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_it(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int32>? data,
    double? timestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_it, [out, data, timestamp]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_st(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int16>? data,
    double? timestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_st, [out, data, timestamp]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_ct(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Char>? data,
    double? timestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_ct, [out, data, timestamp]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_strt(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? data,
    double? timestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_strt, [out, data, timestamp]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_vt(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Void>? data,
    double? timestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_vt, [out, data, timestamp]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_ftp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Float>? data,
    double? timestamp,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_ftp, [
              out,
              data,
              timestamp,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_dtp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Double>? data,
    double? timestamp,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_dtp, [
              out,
              data,
              timestamp,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_ltp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int64>? data,
    double? timestamp,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_ltp, [
              out,
              data,
              timestamp,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_itp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int32>? data,
    double? timestamp,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_itp, [
              out,
              data,
              timestamp,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_stp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int16>? data,
    double? timestamp,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_stp, [
              out,
              data,
              timestamp,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_ctp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Char>? data,
    double? timestamp,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_ctp, [
              out,
              data,
              timestamp,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_strtp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? data,
    double? timestamp,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_strtp, [
              out,
              data,
              timestamp,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_vtp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Void>? data,
    double? timestamp,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_vtp, [
              out,
              data,
              timestamp,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_buf(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? data,
    _i3.Pointer<_i3.Uint32>? lengths,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_buf, [out, data, lengths]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_buft(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? data,
    _i3.Pointer<_i3.Uint32>? lengths,
    double? timestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_buft, [
              out,
              data,
              lengths,
              timestamp,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_sample_buftp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? data,
    _i3.Pointer<_i3.Uint32>? lengths,
    double? timestamp,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_sample_buftp, [
              out,
              data,
              lengths,
              timestamp,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_f(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Float>? data,
    int? data_elements,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_f, [out, data, data_elements]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_d(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Double>? data,
    int? data_elements,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_d, [out, data, data_elements]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_l(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int64>? data,
    int? data_elements,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_l, [out, data, data_elements]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_i(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int32>? data,
    int? data_elements,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_i, [out, data, data_elements]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_s(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int16>? data,
    int? data_elements,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_s, [out, data, data_elements]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_c(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Char>? data,
    int? data_elements,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_c, [out, data, data_elements]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_str(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? data,
    int? data_elements,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_str, [out, data, data_elements]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_ft(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Float>? data,
    int? data_elements,
    double? timestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_ft, [
              out,
              data,
              data_elements,
              timestamp,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_dt(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Double>? data,
    int? data_elements,
    double? timestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_dt, [
              out,
              data,
              data_elements,
              timestamp,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_lt(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int64>? data,
    int? data_elements,
    double? timestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_lt, [
              out,
              data,
              data_elements,
              timestamp,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_it(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int32>? data,
    int? data_elements,
    double? timestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_it, [
              out,
              data,
              data_elements,
              timestamp,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_st(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int16>? data,
    int? data_elements,
    double? timestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_st, [
              out,
              data,
              data_elements,
              timestamp,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_ct(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Char>? data,
    int? data_elements,
    double? timestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_ct, [
              out,
              data,
              data_elements,
              timestamp,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_strt(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? data,
    int? data_elements,
    double? timestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_strt, [
              out,
              data,
              data_elements,
              timestamp,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_ftp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Float>? data,
    int? data_elements,
    double? timestamp,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_ftp, [
              out,
              data,
              data_elements,
              timestamp,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_dtp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Double>? data,
    int? data_elements,
    double? timestamp,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_dtp, [
              out,
              data,
              data_elements,
              timestamp,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_ltp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int64>? data,
    int? data_elements,
    double? timestamp,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_ltp, [
              out,
              data,
              data_elements,
              timestamp,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_itp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int32>? data,
    int? data_elements,
    double? timestamp,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_itp, [
              out,
              data,
              data_elements,
              timestamp,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_stp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int16>? data,
    int? data_elements,
    double? timestamp,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_stp, [
              out,
              data,
              data_elements,
              timestamp,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_ctp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Char>? data,
    int? data_elements,
    double? timestamp,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_ctp, [
              out,
              data,
              data_elements,
              timestamp,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_strtp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? data,
    int? data_elements,
    double? timestamp,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_strtp, [
              out,
              data,
              data_elements,
              timestamp,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_ftn(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Float>? data,
    int? data_elements,
    _i3.Pointer<_i3.Double>? timestamps,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_ftn, [
              out,
              data,
              data_elements,
              timestamps,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_dtn(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Double>? data,
    int? data_elements,
    _i3.Pointer<_i3.Double>? timestamps,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_dtn, [
              out,
              data,
              data_elements,
              timestamps,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_ltn(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int64>? data,
    int? data_elements,
    _i3.Pointer<_i3.Double>? timestamps,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_ltn, [
              out,
              data,
              data_elements,
              timestamps,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_itn(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int32>? data,
    int? data_elements,
    _i3.Pointer<_i3.Double>? timestamps,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_itn, [
              out,
              data,
              data_elements,
              timestamps,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_stn(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int16>? data,
    int? data_elements,
    _i3.Pointer<_i3.Double>? timestamps,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_stn, [
              out,
              data,
              data_elements,
              timestamps,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_ctn(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Char>? data,
    int? data_elements,
    _i3.Pointer<_i3.Double>? timestamps,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_ctn, [
              out,
              data,
              data_elements,
              timestamps,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_strtn(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? data,
    int? data_elements,
    _i3.Pointer<_i3.Double>? timestamps,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_strtn, [
              out,
              data,
              data_elements,
              timestamps,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_ftnp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Float>? data,
    int? data_elements,
    _i3.Pointer<_i3.Double>? timestamps,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_ftnp, [
              out,
              data,
              data_elements,
              timestamps,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_dtnp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Double>? data,
    int? data_elements,
    _i3.Pointer<_i3.Double>? timestamps,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_dtnp, [
              out,
              data,
              data_elements,
              timestamps,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_ltnp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int64>? data,
    int? data_elements,
    _i3.Pointer<_i3.Double>? timestamps,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_ltnp, [
              out,
              data,
              data_elements,
              timestamps,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_itnp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int32>? data,
    int? data_elements,
    _i3.Pointer<_i3.Double>? timestamps,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_itnp, [
              out,
              data,
              data_elements,
              timestamps,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_stnp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Int16>? data,
    int? data_elements,
    _i3.Pointer<_i3.Double>? timestamps,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_stnp, [
              out,
              data,
              data_elements,
              timestamps,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_ctnp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Char>? data,
    int? data_elements,
    _i3.Pointer<_i3.Double>? timestamps,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_ctnp, [
              out,
              data,
              data_elements,
              timestamps,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_strtnp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? data,
    int? data_elements,
    _i3.Pointer<_i3.Double>? timestamps,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_strtnp, [
              out,
              data,
              data_elements,
              timestamps,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_buf(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? data,
    _i3.Pointer<_i3.Uint32>? lengths,
    int? data_elements,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_buf, [
              out,
              data,
              lengths,
              data_elements,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_buft(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? data,
    _i3.Pointer<_i3.Uint32>? lengths,
    int? data_elements,
    double? timestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_buft, [
              out,
              data,
              lengths,
              data_elements,
              timestamp,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_buftp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? data,
    _i3.Pointer<_i3.Uint32>? lengths,
    int? data_elements,
    double? timestamp,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_buftp, [
              out,
              data,
              lengths,
              data_elements,
              timestamp,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_buftn(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? data,
    _i3.Pointer<_i3.Uint32>? lengths,
    int? data_elements,
    _i3.Pointer<_i3.Double>? timestamps,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_buftn, [
              out,
              data,
              lengths,
              data_elements,
              timestamps,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_push_chunk_buftnp(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? data,
    _i3.Pointer<_i3.Uint32>? lengths,
    int? data_elements,
    _i3.Pointer<_i3.Double>? timestamps,
    int? pushthrough,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_push_chunk_buftnp, [
              out,
              data,
              lengths,
              data_elements,
              timestamps,
              pushthrough,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_have_consumers(_i3.Pointer<_i2.lsl_outlet_struct_>? out) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_have_consumers, [out]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_wait_for_consumers(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
    double? timeout,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_wait_for_consumers, [out, timeout]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i3.Pointer<_i2.lsl_streaminfo_struct_> lsl_get_info(
    _i3.Pointer<_i2.lsl_outlet_struct_>? out,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_get_info, [out]),
            returnValue: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_streaminfo_struct_>>(
                  this,
                  Invocation.method(#lsl_get_info, [out]),
                ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_streaminfo_struct_>>(
                  this,
                  Invocation.method(#lsl_get_info, [out]),
                ),
          )
          as _i3.Pointer<_i2.lsl_streaminfo_struct_>);

  @override
  _i3.Pointer<_i3.Char> lsl_last_error() =>
      (super.noSuchMethod(
            Invocation.method(#lsl_last_error, []),
            returnValue: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_last_error, []),
            ),
            returnValueForMissingStub: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_last_error, []),
            ),
          )
          as _i3.Pointer<_i3.Char>);

  @override
  int lsl_protocol_version() =>
      (super.noSuchMethod(
            Invocation.method(#lsl_protocol_version, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_library_version() =>
      (super.noSuchMethod(
            Invocation.method(#lsl_library_version, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i3.Pointer<_i3.Char> lsl_library_info() =>
      (super.noSuchMethod(
            Invocation.method(#lsl_library_info, []),
            returnValue: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_library_info, []),
            ),
            returnValueForMissingStub: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_library_info, []),
            ),
          )
          as _i3.Pointer<_i3.Char>);

  @override
  double lsl_local_clock() =>
      (super.noSuchMethod(
            Invocation.method(#lsl_local_clock, []),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  void lsl_destroy_string(_i3.Pointer<_i3.Char>? s) => super.noSuchMethod(
    Invocation.method(#lsl_destroy_string, [s]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Pointer<_i2.lsl_inlet_struct_> lsl_create_inlet(
    _i3.Pointer<_i2.lsl_streaminfo_struct_>? info,
    int? max_buflen,
    int? max_chunklen,
    int? recover,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_create_inlet, [
              info,
              max_buflen,
              max_chunklen,
              recover,
            ]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i2.lsl_inlet_struct_>>(
              this,
              Invocation.method(#lsl_create_inlet, [
                info,
                max_buflen,
                max_chunklen,
                recover,
              ]),
            ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_inlet_struct_>>(
                  this,
                  Invocation.method(#lsl_create_inlet, [
                    info,
                    max_buflen,
                    max_chunklen,
                    recover,
                  ]),
                ),
          )
          as _i3.Pointer<_i2.lsl_inlet_struct_>);

  @override
  _i3.Pointer<_i2.lsl_inlet_struct_> lsl_create_inlet_ex(
    _i3.Pointer<_i2.lsl_streaminfo_struct_>? info,
    int? max_buflen,
    int? max_chunklen,
    int? recover,
    _i2.lsl_transport_options_t? flags,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_create_inlet_ex, [
              info,
              max_buflen,
              max_chunklen,
              recover,
              flags,
            ]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i2.lsl_inlet_struct_>>(
              this,
              Invocation.method(#lsl_create_inlet_ex, [
                info,
                max_buflen,
                max_chunklen,
                recover,
                flags,
              ]),
            ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_inlet_struct_>>(
                  this,
                  Invocation.method(#lsl_create_inlet_ex, [
                    info,
                    max_buflen,
                    max_chunklen,
                    recover,
                    flags,
                  ]),
                ),
          )
          as _i3.Pointer<_i2.lsl_inlet_struct_>);

  @override
  void lsl_destroy_inlet(_i3.Pointer<_i2.lsl_inlet_struct_>? in1) =>
      super.noSuchMethod(
        Invocation.method(#lsl_destroy_inlet, [in1]),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Pointer<_i2.lsl_streaminfo_struct_> lsl_get_fullinfo(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_get_fullinfo, [in1, timeout, ec]),
            returnValue: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_streaminfo_struct_>>(
                  this,
                  Invocation.method(#lsl_get_fullinfo, [in1, timeout, ec]),
                ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_streaminfo_struct_>>(
                  this,
                  Invocation.method(#lsl_get_fullinfo, [in1, timeout, ec]),
                ),
          )
          as _i3.Pointer<_i2.lsl_streaminfo_struct_>);

  @override
  void lsl_open_stream(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) => super.noSuchMethod(
    Invocation.method(#lsl_open_stream, [in1, timeout, ec]),
    returnValueForMissingStub: null,
  );

  @override
  void lsl_close_stream(_i3.Pointer<_i2.lsl_inlet_struct_>? in1) =>
      super.noSuchMethod(
        Invocation.method(#lsl_close_stream, [in1]),
        returnValueForMissingStub: null,
      );

  @override
  double lsl_time_correction(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_time_correction, [in1, timeout, ec]),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double lsl_time_correction_ex(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    _i3.Pointer<_i3.Double>? remote_time,
    _i3.Pointer<_i3.Double>? uncertainty,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_time_correction_ex, [
              in1,
              remote_time,
              uncertainty,
              timeout,
              ec,
            ]),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  int lsl_set_postprocessing(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    int? flags,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_set_postprocessing, [in1, flags]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  double lsl_pull_sample_f(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    _i3.Pointer<_i3.Float>? buffer,
    int? buffer_elements,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_pull_sample_f, [
              in1,
              buffer,
              buffer_elements,
              timeout,
              ec,
            ]),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double lsl_pull_sample_d(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    _i3.Pointer<_i3.Double>? buffer,
    int? buffer_elements,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_pull_sample_d, [
              in1,
              buffer,
              buffer_elements,
              timeout,
              ec,
            ]),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double lsl_pull_sample_l(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    _i3.Pointer<_i3.Int64>? buffer,
    int? buffer_elements,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_pull_sample_l, [
              in1,
              buffer,
              buffer_elements,
              timeout,
              ec,
            ]),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double lsl_pull_sample_i(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    _i3.Pointer<_i3.Int32>? buffer,
    int? buffer_elements,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_pull_sample_i, [
              in1,
              buffer,
              buffer_elements,
              timeout,
              ec,
            ]),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double lsl_pull_sample_s(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    _i3.Pointer<_i3.Int16>? buffer,
    int? buffer_elements,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_pull_sample_s, [
              in1,
              buffer,
              buffer_elements,
              timeout,
              ec,
            ]),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double lsl_pull_sample_c(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    _i3.Pointer<_i3.Char>? buffer,
    int? buffer_elements,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_pull_sample_c, [
              in1,
              buffer,
              buffer_elements,
              timeout,
              ec,
            ]),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double lsl_pull_sample_str(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? buffer,
    int? buffer_elements,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_pull_sample_str, [
              in1,
              buffer,
              buffer_elements,
              timeout,
              ec,
            ]),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double lsl_pull_sample_buf(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? buffer,
    _i3.Pointer<_i3.Uint32>? buffer_lengths,
    int? buffer_elements,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_pull_sample_buf, [
              in1,
              buffer,
              buffer_lengths,
              buffer_elements,
              timeout,
              ec,
            ]),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double lsl_pull_sample_v(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    _i3.Pointer<_i3.Void>? buffer,
    int? buffer_bytes,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_pull_sample_v, [
              in1,
              buffer,
              buffer_bytes,
              timeout,
              ec,
            ]),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  int lsl_pull_chunk_f(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    _i3.Pointer<_i3.Float>? data_buffer,
    _i3.Pointer<_i3.Double>? timestamp_buffer,
    int? data_buffer_elements,
    int? timestamp_buffer_elements,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_pull_chunk_f, [
              in1,
              data_buffer,
              timestamp_buffer,
              data_buffer_elements,
              timestamp_buffer_elements,
              timeout,
              ec,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_pull_chunk_d(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    _i3.Pointer<_i3.Double>? data_buffer,
    _i3.Pointer<_i3.Double>? timestamp_buffer,
    int? data_buffer_elements,
    int? timestamp_buffer_elements,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_pull_chunk_d, [
              in1,
              data_buffer,
              timestamp_buffer,
              data_buffer_elements,
              timestamp_buffer_elements,
              timeout,
              ec,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_pull_chunk_l(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    _i3.Pointer<_i3.Int64>? data_buffer,
    _i3.Pointer<_i3.Double>? timestamp_buffer,
    int? data_buffer_elements,
    int? timestamp_buffer_elements,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_pull_chunk_l, [
              in1,
              data_buffer,
              timestamp_buffer,
              data_buffer_elements,
              timestamp_buffer_elements,
              timeout,
              ec,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_pull_chunk_i(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    _i3.Pointer<_i3.Int32>? data_buffer,
    _i3.Pointer<_i3.Double>? timestamp_buffer,
    int? data_buffer_elements,
    int? timestamp_buffer_elements,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_pull_chunk_i, [
              in1,
              data_buffer,
              timestamp_buffer,
              data_buffer_elements,
              timestamp_buffer_elements,
              timeout,
              ec,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_pull_chunk_s(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    _i3.Pointer<_i3.Int16>? data_buffer,
    _i3.Pointer<_i3.Double>? timestamp_buffer,
    int? data_buffer_elements,
    int? timestamp_buffer_elements,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_pull_chunk_s, [
              in1,
              data_buffer,
              timestamp_buffer,
              data_buffer_elements,
              timestamp_buffer_elements,
              timeout,
              ec,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_pull_chunk_c(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    _i3.Pointer<_i3.Char>? data_buffer,
    _i3.Pointer<_i3.Double>? timestamp_buffer,
    int? data_buffer_elements,
    int? timestamp_buffer_elements,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_pull_chunk_c, [
              in1,
              data_buffer,
              timestamp_buffer,
              data_buffer_elements,
              timestamp_buffer_elements,
              timeout,
              ec,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_pull_chunk_str(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? data_buffer,
    _i3.Pointer<_i3.Double>? timestamp_buffer,
    int? data_buffer_elements,
    int? timestamp_buffer_elements,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_pull_chunk_str, [
              in1,
              data_buffer,
              timestamp_buffer,
              data_buffer_elements,
              timestamp_buffer_elements,
              timeout,
              ec,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_pull_chunk_buf(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    _i3.Pointer<_i3.Pointer<_i3.Char>>? data_buffer,
    _i3.Pointer<_i3.Uint32>? lengths_buffer,
    _i3.Pointer<_i3.Double>? timestamp_buffer,
    int? data_buffer_elements,
    int? timestamp_buffer_elements,
    double? timeout,
    _i3.Pointer<_i3.Int32>? ec,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_pull_chunk_buf, [
              in1,
              data_buffer,
              lengths_buffer,
              timestamp_buffer,
              data_buffer_elements,
              timestamp_buffer_elements,
              timeout,
              ec,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_samples_available(_i3.Pointer<_i2.lsl_inlet_struct_>? in1) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_samples_available, [in1]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_inlet_flush(_i3.Pointer<_i2.lsl_inlet_struct_>? in1) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_inlet_flush, [in1]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_was_clock_reset(_i3.Pointer<_i2.lsl_inlet_struct_>? in1) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_was_clock_reset, [in1]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_smoothing_halftime(
    _i3.Pointer<_i2.lsl_inlet_struct_>? in1,
    double? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_smoothing_halftime, [in1, value]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i3.Pointer<_i2.lsl_streaminfo_struct_> lsl_create_streaminfo(
    _i3.Pointer<_i3.Char>? name,
    _i3.Pointer<_i3.Char>? type,
    int? channel_count,
    double? nominal_srate,
    _i2.lsl_channel_format_t? channel_format,
    _i3.Pointer<_i3.Char>? source_id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_create_streaminfo, [
              name,
              type,
              channel_count,
              nominal_srate,
              channel_format,
              source_id,
            ]),
            returnValue: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_streaminfo_struct_>>(
                  this,
                  Invocation.method(#lsl_create_streaminfo, [
                    name,
                    type,
                    channel_count,
                    nominal_srate,
                    channel_format,
                    source_id,
                  ]),
                ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_streaminfo_struct_>>(
                  this,
                  Invocation.method(#lsl_create_streaminfo, [
                    name,
                    type,
                    channel_count,
                    nominal_srate,
                    channel_format,
                    source_id,
                  ]),
                ),
          )
          as _i3.Pointer<_i2.lsl_streaminfo_struct_>);

  @override
  void lsl_destroy_streaminfo(_i3.Pointer<_i2.lsl_streaminfo_struct_>? info) =>
      super.noSuchMethod(
        Invocation.method(#lsl_destroy_streaminfo, [info]),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Pointer<_i2.lsl_streaminfo_struct_> lsl_copy_streaminfo(
    _i3.Pointer<_i2.lsl_streaminfo_struct_>? info,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_copy_streaminfo, [info]),
            returnValue: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_streaminfo_struct_>>(
                  this,
                  Invocation.method(#lsl_copy_streaminfo, [info]),
                ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_streaminfo_struct_>>(
                  this,
                  Invocation.method(#lsl_copy_streaminfo, [info]),
                ),
          )
          as _i3.Pointer<_i2.lsl_streaminfo_struct_>);

  @override
  _i3.Pointer<_i3.Char> lsl_get_name(
    _i3.Pointer<_i2.lsl_streaminfo_struct_>? info,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_get_name, [info]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_get_name, [info]),
            ),
            returnValueForMissingStub: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_get_name, [info]),
            ),
          )
          as _i3.Pointer<_i3.Char>);

  @override
  _i3.Pointer<_i3.Char> lsl_get_type(
    _i3.Pointer<_i2.lsl_streaminfo_struct_>? info,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_get_type, [info]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_get_type, [info]),
            ),
            returnValueForMissingStub: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_get_type, [info]),
            ),
          )
          as _i3.Pointer<_i3.Char>);

  @override
  int lsl_get_channel_count(_i3.Pointer<_i2.lsl_streaminfo_struct_>? info) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_get_channel_count, [info]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  double lsl_get_nominal_srate(_i3.Pointer<_i2.lsl_streaminfo_struct_>? info) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_get_nominal_srate, [info]),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  _i2.lsl_channel_format_t lsl_get_channel_format(
    _i3.Pointer<_i2.lsl_streaminfo_struct_>? info,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_get_channel_format, [info]),
            returnValue: _i2.lsl_channel_format_t.cft_float32,
            returnValueForMissingStub: _i2.lsl_channel_format_t.cft_float32,
          )
          as _i2.lsl_channel_format_t);

  @override
  _i3.Pointer<_i3.Char> lsl_get_source_id(
    _i3.Pointer<_i2.lsl_streaminfo_struct_>? info,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_get_source_id, [info]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_get_source_id, [info]),
            ),
            returnValueForMissingStub: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_get_source_id, [info]),
            ),
          )
          as _i3.Pointer<_i3.Char>);

  @override
  int lsl_get_version(_i3.Pointer<_i2.lsl_streaminfo_struct_>? info) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_get_version, [info]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  double lsl_get_created_at(_i3.Pointer<_i2.lsl_streaminfo_struct_>? info) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_get_created_at, [info]),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  _i3.Pointer<_i3.Char> lsl_get_uid(
    _i3.Pointer<_i2.lsl_streaminfo_struct_>? info,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_get_uid, [info]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_get_uid, [info]),
            ),
            returnValueForMissingStub: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_get_uid, [info]),
            ),
          )
          as _i3.Pointer<_i3.Char>);

  @override
  _i3.Pointer<_i3.Char> lsl_get_session_id(
    _i3.Pointer<_i2.lsl_streaminfo_struct_>? info,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_get_session_id, [info]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_get_session_id, [info]),
            ),
            returnValueForMissingStub: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_get_session_id, [info]),
            ),
          )
          as _i3.Pointer<_i3.Char>);

  @override
  _i3.Pointer<_i3.Char> lsl_get_hostname(
    _i3.Pointer<_i2.lsl_streaminfo_struct_>? info,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_get_hostname, [info]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_get_hostname, [info]),
            ),
            returnValueForMissingStub: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_get_hostname, [info]),
            ),
          )
          as _i3.Pointer<_i3.Char>);

  @override
  _i3.Pointer<_i2.lsl_xml_ptr_struct_> lsl_get_desc(
    _i3.Pointer<_i2.lsl_streaminfo_struct_>? info,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_get_desc, [info]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
              this,
              Invocation.method(#lsl_get_desc, [info]),
            ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
                  this,
                  Invocation.method(#lsl_get_desc, [info]),
                ),
          )
          as _i3.Pointer<_i2.lsl_xml_ptr_struct_>);

  @override
  _i3.Pointer<_i3.Char> lsl_get_xml(
    _i3.Pointer<_i2.lsl_streaminfo_struct_>? info,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_get_xml, [info]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_get_xml, [info]),
            ),
            returnValueForMissingStub: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_get_xml, [info]),
            ),
          )
          as _i3.Pointer<_i3.Char>);

  @override
  int lsl_get_channel_bytes(_i3.Pointer<_i2.lsl_streaminfo_struct_>? info) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_get_channel_bytes, [info]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_get_sample_bytes(_i3.Pointer<_i2.lsl_streaminfo_struct_>? info) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_get_sample_bytes, [info]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_stream_info_matches_query(
    _i3.Pointer<_i2.lsl_streaminfo_struct_>? info,
    _i3.Pointer<_i3.Char>? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_stream_info_matches_query, [info, query]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i3.Pointer<_i2.lsl_streaminfo_struct_> lsl_streaminfo_from_xml(
    _i3.Pointer<_i3.Char>? xml,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_streaminfo_from_xml, [xml]),
            returnValue: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_streaminfo_struct_>>(
                  this,
                  Invocation.method(#lsl_streaminfo_from_xml, [xml]),
                ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_streaminfo_struct_>>(
                  this,
                  Invocation.method(#lsl_streaminfo_from_xml, [xml]),
                ),
          )
          as _i3.Pointer<_i2.lsl_streaminfo_struct_>);

  @override
  _i3.Pointer<_i2.lsl_xml_ptr_struct_> lsl_first_child(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_first_child, [e]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
              this,
              Invocation.method(#lsl_first_child, [e]),
            ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
                  this,
                  Invocation.method(#lsl_first_child, [e]),
                ),
          )
          as _i3.Pointer<_i2.lsl_xml_ptr_struct_>);

  @override
  _i3.Pointer<_i2.lsl_xml_ptr_struct_> lsl_last_child(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_last_child, [e]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
              this,
              Invocation.method(#lsl_last_child, [e]),
            ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
                  this,
                  Invocation.method(#lsl_last_child, [e]),
                ),
          )
          as _i3.Pointer<_i2.lsl_xml_ptr_struct_>);

  @override
  _i3.Pointer<_i2.lsl_xml_ptr_struct_> lsl_next_sibling(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_next_sibling, [e]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
              this,
              Invocation.method(#lsl_next_sibling, [e]),
            ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
                  this,
                  Invocation.method(#lsl_next_sibling, [e]),
                ),
          )
          as _i3.Pointer<_i2.lsl_xml_ptr_struct_>);

  @override
  _i3.Pointer<_i2.lsl_xml_ptr_struct_> lsl_previous_sibling(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_previous_sibling, [e]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
              this,
              Invocation.method(#lsl_previous_sibling, [e]),
            ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
                  this,
                  Invocation.method(#lsl_previous_sibling, [e]),
                ),
          )
          as _i3.Pointer<_i2.lsl_xml_ptr_struct_>);

  @override
  _i3.Pointer<_i2.lsl_xml_ptr_struct_> lsl_parent(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_parent, [e]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
              this,
              Invocation.method(#lsl_parent, [e]),
            ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
                  this,
                  Invocation.method(#lsl_parent, [e]),
                ),
          )
          as _i3.Pointer<_i2.lsl_xml_ptr_struct_>);

  @override
  _i3.Pointer<_i2.lsl_xml_ptr_struct_> lsl_child(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
    _i3.Pointer<_i3.Char>? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_child, [e, name]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
              this,
              Invocation.method(#lsl_child, [e, name]),
            ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
                  this,
                  Invocation.method(#lsl_child, [e, name]),
                ),
          )
          as _i3.Pointer<_i2.lsl_xml_ptr_struct_>);

  @override
  _i3.Pointer<_i2.lsl_xml_ptr_struct_> lsl_next_sibling_n(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
    _i3.Pointer<_i3.Char>? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_next_sibling_n, [e, name]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
              this,
              Invocation.method(#lsl_next_sibling_n, [e, name]),
            ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
                  this,
                  Invocation.method(#lsl_next_sibling_n, [e, name]),
                ),
          )
          as _i3.Pointer<_i2.lsl_xml_ptr_struct_>);

  @override
  _i3.Pointer<_i2.lsl_xml_ptr_struct_> lsl_previous_sibling_n(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
    _i3.Pointer<_i3.Char>? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_previous_sibling_n, [e, name]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
              this,
              Invocation.method(#lsl_previous_sibling_n, [e, name]),
            ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
                  this,
                  Invocation.method(#lsl_previous_sibling_n, [e, name]),
                ),
          )
          as _i3.Pointer<_i2.lsl_xml_ptr_struct_>);

  @override
  int lsl_empty(_i3.Pointer<_i2.lsl_xml_ptr_struct_>? e) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_empty, [e]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_is_text(_i3.Pointer<_i2.lsl_xml_ptr_struct_>? e) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_is_text, [e]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i3.Pointer<_i3.Char> lsl_name(_i3.Pointer<_i2.lsl_xml_ptr_struct_>? e) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_name, [e]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_name, [e]),
            ),
            returnValueForMissingStub: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_name, [e]),
            ),
          )
          as _i3.Pointer<_i3.Char>);

  @override
  _i3.Pointer<_i3.Char> lsl_value(_i3.Pointer<_i2.lsl_xml_ptr_struct_>? e) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_value, [e]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_value, [e]),
            ),
            returnValueForMissingStub: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_value, [e]),
            ),
          )
          as _i3.Pointer<_i3.Char>);

  @override
  _i3.Pointer<_i3.Char> lsl_child_value(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_child_value, [e]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_child_value, [e]),
            ),
            returnValueForMissingStub: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_child_value, [e]),
            ),
          )
          as _i3.Pointer<_i3.Char>);

  @override
  _i3.Pointer<_i3.Char> lsl_child_value_n(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
    _i3.Pointer<_i3.Char>? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_child_value_n, [e, name]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_child_value_n, [e, name]),
            ),
            returnValueForMissingStub: _i4.dummyValue<_i3.Pointer<_i3.Char>>(
              this,
              Invocation.method(#lsl_child_value_n, [e, name]),
            ),
          )
          as _i3.Pointer<_i3.Char>);

  @override
  _i3.Pointer<_i2.lsl_xml_ptr_struct_> lsl_append_child_value(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
    _i3.Pointer<_i3.Char>? name,
    _i3.Pointer<_i3.Char>? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_append_child_value, [e, name, value]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
              this,
              Invocation.method(#lsl_append_child_value, [e, name, value]),
            ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
                  this,
                  Invocation.method(#lsl_append_child_value, [e, name, value]),
                ),
          )
          as _i3.Pointer<_i2.lsl_xml_ptr_struct_>);

  @override
  _i3.Pointer<_i2.lsl_xml_ptr_struct_> lsl_prepend_child_value(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
    _i3.Pointer<_i3.Char>? name,
    _i3.Pointer<_i3.Char>? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_prepend_child_value, [e, name, value]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
              this,
              Invocation.method(#lsl_prepend_child_value, [e, name, value]),
            ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
                  this,
                  Invocation.method(#lsl_prepend_child_value, [e, name, value]),
                ),
          )
          as _i3.Pointer<_i2.lsl_xml_ptr_struct_>);

  @override
  int lsl_set_child_value(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
    _i3.Pointer<_i3.Char>? name,
    _i3.Pointer<_i3.Char>? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_set_child_value, [e, name, value]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_set_name(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
    _i3.Pointer<_i3.Char>? rhs,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_set_name, [e, rhs]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_set_value(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
    _i3.Pointer<_i3.Char>? rhs,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_set_value, [e, rhs]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i3.Pointer<_i2.lsl_xml_ptr_struct_> lsl_append_child(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
    _i3.Pointer<_i3.Char>? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_append_child, [e, name]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
              this,
              Invocation.method(#lsl_append_child, [e, name]),
            ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
                  this,
                  Invocation.method(#lsl_append_child, [e, name]),
                ),
          )
          as _i3.Pointer<_i2.lsl_xml_ptr_struct_>);

  @override
  _i3.Pointer<_i2.lsl_xml_ptr_struct_> lsl_prepend_child(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
    _i3.Pointer<_i3.Char>? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_prepend_child, [e, name]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
              this,
              Invocation.method(#lsl_prepend_child, [e, name]),
            ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
                  this,
                  Invocation.method(#lsl_prepend_child, [e, name]),
                ),
          )
          as _i3.Pointer<_i2.lsl_xml_ptr_struct_>);

  @override
  _i3.Pointer<_i2.lsl_xml_ptr_struct_> lsl_append_copy(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e2,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_append_copy, [e, e2]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
              this,
              Invocation.method(#lsl_append_copy, [e, e2]),
            ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
                  this,
                  Invocation.method(#lsl_append_copy, [e, e2]),
                ),
          )
          as _i3.Pointer<_i2.lsl_xml_ptr_struct_>);

  @override
  _i3.Pointer<_i2.lsl_xml_ptr_struct_> lsl_prepend_copy(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e2,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_prepend_copy, [e, e2]),
            returnValue: _i4.dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
              this,
              Invocation.method(#lsl_prepend_copy, [e, e2]),
            ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_xml_ptr_struct_>>(
                  this,
                  Invocation.method(#lsl_prepend_copy, [e, e2]),
                ),
          )
          as _i3.Pointer<_i2.lsl_xml_ptr_struct_>);

  @override
  void lsl_remove_child_n(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
    _i3.Pointer<_i3.Char>? name,
  ) => super.noSuchMethod(
    Invocation.method(#lsl_remove_child_n, [e, name]),
    returnValueForMissingStub: null,
  );

  @override
  void lsl_remove_child(
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e,
    _i3.Pointer<_i2.lsl_xml_ptr_struct_>? e2,
  ) => super.noSuchMethod(
    Invocation.method(#lsl_remove_child, [e, e2]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Pointer<_i2.lsl_continuous_resolver_> lsl_create_continuous_resolver(
    double? forget_after,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_create_continuous_resolver, [forget_after]),
            returnValue: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_continuous_resolver_>>(
                  this,
                  Invocation.method(#lsl_create_continuous_resolver, [
                    forget_after,
                  ]),
                ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_continuous_resolver_>>(
                  this,
                  Invocation.method(#lsl_create_continuous_resolver, [
                    forget_after,
                  ]),
                ),
          )
          as _i3.Pointer<_i2.lsl_continuous_resolver_>);

  @override
  _i3.Pointer<_i2.lsl_continuous_resolver_>
  lsl_create_continuous_resolver_byprop(
    _i3.Pointer<_i3.Char>? prop,
    _i3.Pointer<_i3.Char>? value,
    double? forget_after,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_create_continuous_resolver_byprop, [
              prop,
              value,
              forget_after,
            ]),
            returnValue: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_continuous_resolver_>>(
                  this,
                  Invocation.method(#lsl_create_continuous_resolver_byprop, [
                    prop,
                    value,
                    forget_after,
                  ]),
                ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_continuous_resolver_>>(
                  this,
                  Invocation.method(#lsl_create_continuous_resolver_byprop, [
                    prop,
                    value,
                    forget_after,
                  ]),
                ),
          )
          as _i3.Pointer<_i2.lsl_continuous_resolver_>);

  @override
  _i3.Pointer<_i2.lsl_continuous_resolver_>
  lsl_create_continuous_resolver_bypred(
    _i3.Pointer<_i3.Char>? pred,
    double? forget_after,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_create_continuous_resolver_bypred, [
              pred,
              forget_after,
            ]),
            returnValue: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_continuous_resolver_>>(
                  this,
                  Invocation.method(#lsl_create_continuous_resolver_bypred, [
                    pred,
                    forget_after,
                  ]),
                ),
            returnValueForMissingStub: _i4
                .dummyValue<_i3.Pointer<_i2.lsl_continuous_resolver_>>(
                  this,
                  Invocation.method(#lsl_create_continuous_resolver_bypred, [
                    pred,
                    forget_after,
                  ]),
                ),
          )
          as _i3.Pointer<_i2.lsl_continuous_resolver_>);

  @override
  int lsl_resolver_results(
    _i3.Pointer<_i2.lsl_continuous_resolver_>? res,
    _i3.Pointer<_i3.Pointer<_i2.lsl_streaminfo_struct_>>? buffer,
    int? buffer_elements,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_resolver_results, [
              res,
              buffer,
              buffer_elements,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  void lsl_destroy_continuous_resolver(
    _i3.Pointer<_i2.lsl_continuous_resolver_>? res,
  ) => super.noSuchMethod(
    Invocation.method(#lsl_destroy_continuous_resolver, [res]),
    returnValueForMissingStub: null,
  );

  @override
  int lsl_resolve_all(
    _i3.Pointer<_i3.Pointer<_i2.lsl_streaminfo_struct_>>? buffer,
    int? buffer_elements,
    double? wait_time,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_resolve_all, [
              buffer,
              buffer_elements,
              wait_time,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_resolve_byprop(
    _i3.Pointer<_i3.Pointer<_i2.lsl_streaminfo_struct_>>? buffer,
    int? buffer_elements,
    _i3.Pointer<_i3.Char>? prop,
    _i3.Pointer<_i3.Char>? value,
    int? minimum,
    double? timeout,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_resolve_byprop, [
              buffer,
              buffer_elements,
              prop,
              value,
              minimum,
              timeout,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int lsl_resolve_bypred(
    _i3.Pointer<_i3.Pointer<_i2.lsl_streaminfo_struct_>>? buffer,
    int? buffer_elements,
    _i3.Pointer<_i3.Char>? pred,
    int? minimum,
    double? timeout,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lsl_resolve_bypred, [
              buffer,
              buffer_elements,
              pred,
              minimum,
              timeout,
            ]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);
}

/// A class which mocks [MulticastLock].
///
/// See the documentation for Mockito's code generation for more information.
class MockMulticastLock extends _i1.Mock implements _i5.MulticastLock {
  @override
  _i6.Future<String?> getPlatformVersion() =>
      (super.noSuchMethod(
            Invocation.method(#getPlatformVersion, []),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);
}
